# Game variables
MY_BALLS_ARE_RED = False 
TIME_BEFORE_HALT = -1 # value <= 0 --> never stops

# Robot properties
ROBOT_RADIUS = .17

# Sensors
IR_PINS = []
IR_POSITIONS = []

ULT_PINS =[(22,23),(24,25),(26,27),(28,29),(30,31)]
ULT_POSITIONS = [(.16,-108), (.15, -72), (.14, -36), (.15, 0), (.16, 36)]
ULT_TIMEOUT = 4000
MOTOR_CURRENT_PINS = (0,0,0,0)

BALL_IN_SENSOR_PIN = 0
BALL_OUT_SENSOR_PIN = 0

# Motors (current, dir, pwm)
ROLLER_PINS = (8,11,12)
RIGHT_MOTOR_PINS = (8,5,6)
LEFT_MOTOR_PINS = (8,9,10)
HELIX_PINS = (8, 3, 4)
RAMP_SERVO_PIN = 0
SCORER_PIN=0

# Control
RIGHT_MOTOR_MIN = 8
RIGHT_MOTOR_MAX = 127

LEFT_MOTOR_MIN = 8
LEFT_MOTOR_MAX = 127

ROLLER_SPEED=-80
HELIX_SPEED=60

# MOVEMENT CONSTANTS

# Capture ball
CPTRBL_TRANSLATE_SPEED = .3
CPTRBL_ROTATE_SPEED = 0

# Rotate in place
ROTINPL_TRANSLATE_SPEED = .10
ROTINPL_ROTATE_SPEED = .12

# Approach target
APPTGT_TRANSLATE_SPEED = .3
APPTGT_ROTATE_SPEED = .2

# Avoid wall
AVDWLL_TRANSLATE_SPEED = -.3
AVDWLL_ROTATE_SPEED = -0.2

# Follow wall
FW_PHI = 18
FW_DIST_TARGET = .4
FW_TRANSLATE_SPEED = .2
FW_ROTATE_SPEED_SCALE = .1


